# Generated by Django 5.1.3 on 2024-12-14 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('information', models.CharField(max_length=6000)),
                ('photo', models.ImageField(upload_to='author_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=64)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PublishingHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('photo', models.ImageField(upload_to='publishing_house_photo/')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=64)),
                ('publication_date', models.DateTimeField()),
                ('isbn', models.BigIntegerField()),
                ('page', models.IntegerField()),
                ('price', models.FloatField()),
                ('photo', models.ImageField(upload_to='books_photos/')),
                ('info', models.CharField(max_length=6000)),
                ('author_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='store.author')),
                ('category', models.ManyToManyField(related_name='books', to='store.category')),
                ('publishing_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='store.publishinghouse')),
            ],
        ),
    ]
