# Generated by Django 5.1.3 on 2024-12-23 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='store.genre'),
        ),
    ]
