# Generated by Django 5.1.3 on 2025-01-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_book_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='total_quatity',
            new_name='total_quantity',
        ),
    ]
