# Generated by Django 5.1.3 on 2025-01-12 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_total_quatity_cart_total_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
