# Generated by Django 5.1.3 on 2025-01-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='c_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='c_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='cvc',
            field=models.IntegerField(default=1),
        ),
    ]
