# Generated by Django 5.1.3 on 2025-01-21 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_orderitem_order_order_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='books',
        ),
    ]
